# Generated by Django 4.2.27 on 2025-12-20 22:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_classpost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Logo de la boutique (format carré recommandé)",
                max_length=255,
                null=True,
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="degree_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bac", "Baccalauréat"),
                    ("bac1", "Bac+1"),
                    ("bac2", "Bac+2"),
                    ("licence", "Licence (Bac+3)"),
                    ("master1", "Master 1 (Bac+4)"),
                    ("master2", "Master 2 (Bac+5)"),
                    ("doctorat", "Doctorat (Bac+8)"),
                    ("autre", "Autre"),
                ],
                help_text="Niveau d'études actuel",
                max_length=50,
            ),
        ),
    ]
